version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
### Pdf2HtmlEx ################################################
    pdf2htmlex:
      build:
        context: ./pdf2htmlex
        args:
          - WEBSERVICE_PATH=${PDF2HTMLEX_WEBSERVICE_PATH}
      volumes:
        - "${PDF2HTMLEX_VOLUME_DIR}:/pdf"
        - ./pdf2htmlex/webservice/:/webservice/
        - ./pdf2htmlex/init.sh:/init.sh
      ports:
        - "${PDF2HTMLEX_PORT}:8085"
      tty: true
      networks:
        - backend
